# Generated by Django 5.2.5 on 2025-08-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0002_remove_movie_release_date_movie_poster_and_more'),
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
